version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Base Image (Hubot)
          command: |
            VERSION=4.0
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker build -t honestica/redis:$VERSION-$CIRCLE_BUILD_NUM $VERSION
            docker tag honestica/redis:$VERSION-$CIRCLE_BUILD_NUM honestica/hubot:$VERSION-latest
            docker push honestica/hubot:$VERSION-$CIRCLE_BUILD_NUM
            docker push honestica/hubot:$VERSION-latest

workflows:
  version: 2
  update:
    triggers:
      - schedule:
          cron: "0 6 * * 1"
          filters:
            branches:
              only:
                - master